import { MigrationInterface, QueryRunner } from "typeorm";

export class Shorebase1754990236142 implements MigrationInterface {
    name = 'Shorebase1754990236142'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`activity_status\` (\`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`approval_type\` (\`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`approval_status\` (\`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`pass\` tinyint NOT NULL, PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_position\` (\`id\` int NOT NULL AUTO_INCREMENT, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`userId\` int NULL, \`jobTitlePositionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_signature\` (\`id\` int NOT NULL AUTO_INCREMENT, \`fileUrl\` varchar(1023) NOT NULL, \`startedAt\` datetime NOT NULL, \`endedAt\` datetime NOT NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`kcUserId\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`username\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, UNIQUE INDEX \`IDX_278dcdc8d755d484eb020fc3b0\` (\`kcUserId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`timesheet_type\` (\`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`summary_timesheet\` (\`id\` int NOT NULL AUTO_INCREMENT, \`periodeStartDate\` date NOT NULL, \`periodeEndDate\` date NOT NULL, \`issueDate\` date NOT NULL, \`timesheetTypeCode\` varchar(255) NULL, \`contractId\` int NULL, \`shorebaseServiceId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`performa_invoice\` (\`id\` int NOT NULL AUTO_INCREMENT, \`issueDate\` date NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoice\` (\`id\` int NOT NULL AUTO_INCREMENT, \`issueDate\` date NOT NULL, \`taxPercentage\` decimal(22,4) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`approval\` (\`id\` int NOT NULL AUTO_INCREMENT, \`remark\` varchar(255) NOT NULL, \`approvalTypeCode\` varchar(255) NULL, \`timesheetId\` int NULL, \`summaryTimesheetId\` int NULL, \`performaInvoiceId\` int NULL, \`invoiceId\` int NULL, \`approvalWorkflowStageId\` int NULL, \`approvalStatusCode\` varchar(255) NULL, \`userId\` int NULL, \`jobPositionId\` int NULL, \`userSignatureId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`approval_workflow_stage\` (\`id\` int NOT NULL AUTO_INCREMENT, \`level\` int NOT NULL, \`approvalWorkflowId\` int NULL, \`jobPositionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`approval_workflow\` (\`id\` int NOT NULL AUTO_INCREMENT, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`timesheetTypeCode\` varchar(255) NULL, \`contractId\` int NULL, \`subContractorId\` int NULL, \`companyId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contract\` (\`id\` int NOT NULL AUTO_INCREMENT, \`contractNumber\` varchar(255) NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`companyId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sub_contractor\` (\`id\` int NOT NULL AUTO_INCREMENT, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`contractId\` int NULL, \`companyId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`activity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`planAmount\` double NULL, \`planDate\` date NULL, \`planDescription\` varchar(1023) NULL, \`actualAmount\` double NULL, \`actualStartedAt\` datetime NULL, \`actualendedAt\` datetime NULL, \`actualDescription\` varchar(1023) NOT NULL, \`activityStatusCode\` varchar(255) NULL, \`timesheetTypeCode\` varchar(255) NULL, \`contractServiceId\` int NULL, \`subContractorId\` int NULL, \`companyId\` int NULL, \`shorebaseServiceId\` int NULL, \`uomCode\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`timesheet_activity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`remarks\` varchar(1023) NULL, \`timesheetId\` int NULL, \`activityId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`timesheet\` (\`id\` int NOT NULL AUTO_INCREMENT, \`totalAmount\` double NOT NULL, \`issueDate\` date NOT NULL, \`timesheetTypeCode\` varchar(255) NULL, \`contractServiceId\` int NULL, \`subContractorId\` int NULL, \`companyId\` int NULL, \`shorebaseServiceId\` int NULL, \`uomCode\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`st_timesheet\` (\`id\` int NOT NULL AUTO_INCREMENT, \`stComponentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contract_service_price\` (\`id\` int NOT NULL AUTO_INCREMENT, \`pricePerUom\` decimal(22,4) NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`contractServiceId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`st_component\` (\`id\` int NOT NULL AUTO_INCREMENT, \`actualPricePerUom\` decimal(22,4) NOT NULL, \`summaryTimesheetId\` int NULL, \`contractServiceId\` int NULL, \`shorebaseServiceId\` int NULL, \`uomCode\` varchar(255) NULL, \`contractServicePriceId\` int NULL, \`shorebaseServicePriceId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shorebase_service_price\` (\`id\` int NOT NULL AUTO_INCREMENT, \`pricePerUom\` decimal(22,4) NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`shorebaseServicesId\` int NULL, \`companiesId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shorebase_service\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` varchar(1023) NOT NULL, \`deafult_price_per_uom\` decimal(22,4) NOT NULL, \`active\` tinyint NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`uomCode\` varchar(255) NULL, UNIQUE INDEX \`IDX_1c806db645eb23c78d6a95294e\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`uo_m\` (\`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sum_calc\` (\`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contract_service\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`contractId\` int NULL, \`serviceId\` int NULL, \`companyId\` int NULL, \`uomCode\` varchar(255) NULL, \`sumCalcCode\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`internal\` tinyint NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`job_title\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`job_position\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`companyId\` int NULL, \`jobTitleId\` int NULL, \`parentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_position\` ADD CONSTRAINT \`FK_1b7679d1ea0ca6182710e888fcb\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`user_position\` ADD CONSTRAINT \`FK_a181d19410343624fa0d3b268fb\` FOREIGN KEY (\`jobTitlePositionId\`) REFERENCES \`job_position\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`user_signature\` ADD CONSTRAINT \`FK_9e0019f81ef0e22e0f7945240f5\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`summary_timesheet\` ADD CONSTRAINT \`FK_ca34cf0b0c7bf4dc9c01fa5f326\` FOREIGN KEY (\`timesheetTypeCode\`) REFERENCES \`timesheet_type\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`summary_timesheet\` ADD CONSTRAINT \`FK_addde76f5823a21d75d9b5535da\` FOREIGN KEY (\`contractId\`) REFERENCES \`contract\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`summary_timesheet\` ADD CONSTRAINT \`FK_7e039b0bf55489b9f9f6a21ffa9\` FOREIGN KEY (\`shorebaseServiceId\`) REFERENCES \`shorebase_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_6a05161b24197a85d8067fce714\` FOREIGN KEY (\`approvalTypeCode\`) REFERENCES \`approval_type\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_289341bdda412b7fd1e1e49d35a\` FOREIGN KEY (\`timesheetId\`) REFERENCES \`timesheet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_f3b13e6a0dd01b4baa7674a47dc\` FOREIGN KEY (\`summaryTimesheetId\`) REFERENCES \`summary_timesheet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_d7fe65cdd32f9c504a9b4797278\` FOREIGN KEY (\`performaInvoiceId\`) REFERENCES \`performa_invoice\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_1cfbcd649d77e715d8595e2fbb3\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoice\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_d4d9962befb2715a006e1b9a633\` FOREIGN KEY (\`approvalWorkflowStageId\`) REFERENCES \`approval_workflow_stage\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_48df81ae866b7affa930dff4b79\` FOREIGN KEY (\`approvalStatusCode\`) REFERENCES \`approval_status\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_f72b9f75117746878f7b44012ee\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_2c03b114e16befcc99d77a7bc2f\` FOREIGN KEY (\`jobPositionId\`) REFERENCES \`job_position\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval\` ADD CONSTRAINT \`FK_f51cce93e344f0ec434dfa2b49a\` FOREIGN KEY (\`userSignatureId\`) REFERENCES \`user_signature\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_workflow_stage\` ADD CONSTRAINT \`FK_d2286d604120f793499ce8b419e\` FOREIGN KEY (\`approvalWorkflowId\`) REFERENCES \`approval_workflow\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_workflow_stage\` ADD CONSTRAINT \`FK_3885d1beda753ab0d593af75f0f\` FOREIGN KEY (\`jobPositionId\`) REFERENCES \`job_position\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_workflow\` ADD CONSTRAINT \`FK_bf9bab0e130a0679814fc01ab51\` FOREIGN KEY (\`timesheetTypeCode\`) REFERENCES \`timesheet_type\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_workflow\` ADD CONSTRAINT \`FK_1c216785ba911e94965fa534ca2\` FOREIGN KEY (\`contractId\`) REFERENCES \`contract\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_workflow\` ADD CONSTRAINT \`FK_8cf501bac996196ccd9a946f1df\` FOREIGN KEY (\`subContractorId\`) REFERENCES \`sub_contractor\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_workflow\` ADD CONSTRAINT \`FK_b5c938c6c1e5d01e98609949909\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract\` ADD CONSTRAINT \`FK_ba4311c222bf9285d9d06f3b477\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`sub_contractor\` ADD CONSTRAINT \`FK_90e28e0a19230b5d4a392f7a162\` FOREIGN KEY (\`contractId\`) REFERENCES \`contract\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sub_contractor\` ADD CONSTRAINT \`FK_a02d4c72cafec665def1782a7e3\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_9e33c5fd2fb069d6ed3974496a7\` FOREIGN KEY (\`activityStatusCode\`) REFERENCES \`activity_status\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_878912d8dd0561d68f53c0f3a37\` FOREIGN KEY (\`timesheetTypeCode\`) REFERENCES \`timesheet_type\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_6f5deb55ae067e8a056322ece9a\` FOREIGN KEY (\`contractServiceId\`) REFERENCES \`contract_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_097e3a0060d8378f8676f57f879\` FOREIGN KEY (\`subContractorId\`) REFERENCES \`sub_contractor\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_d6283f57727d60c94cc72a31916\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_cd03d765b6008f724fccb3c1cd7\` FOREIGN KEY (\`shorebaseServiceId\`) REFERENCES \`shorebase_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_a3be35ce844d95f1a4ec75b3852\` FOREIGN KEY (\`uomCode\`) REFERENCES \`uo_m\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timesheet_activity\` ADD CONSTRAINT \`FK_97a61b2c03ed827486806ab451e\` FOREIGN KEY (\`timesheetId\`) REFERENCES \`timesheet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timesheet_activity\` ADD CONSTRAINT \`FK_9f1c03e7735a96b1e5497f553cb\` FOREIGN KEY (\`activityId\`) REFERENCES \`activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timesheet\` ADD CONSTRAINT \`FK_311d5e800cd6b644d427a2d34b9\` FOREIGN KEY (\`timesheetTypeCode\`) REFERENCES \`timesheet_type\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timesheet\` ADD CONSTRAINT \`FK_34e68bf7bcf593c3b40436a13a3\` FOREIGN KEY (\`contractServiceId\`) REFERENCES \`contract_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timesheet\` ADD CONSTRAINT \`FK_37349385c493b325e4ef4671078\` FOREIGN KEY (\`subContractorId\`) REFERENCES \`sub_contractor\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timesheet\` ADD CONSTRAINT \`FK_20fe7c662cd0dfc3a38979e4630\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timesheet\` ADD CONSTRAINT \`FK_727931c1dbed8548e8c3a21697c\` FOREIGN KEY (\`shorebaseServiceId\`) REFERENCES \`shorebase_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timesheet\` ADD CONSTRAINT \`FK_496744bcf637a12e544804e2d88\` FOREIGN KEY (\`uomCode\`) REFERENCES \`uo_m\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`st_timesheet\` ADD CONSTRAINT \`FK_b8dc581b044bc5bede6e6dba8fc\` FOREIGN KEY (\`stComponentId\`) REFERENCES \`st_component\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_service_price\` ADD CONSTRAINT \`FK_03d9f74aa59619046e86d08f7b8\` FOREIGN KEY (\`contractServiceId\`) REFERENCES \`contract_service\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`st_component\` ADD CONSTRAINT \`FK_c274a8a1ba06a6d7aee8b13ada3\` FOREIGN KEY (\`summaryTimesheetId\`) REFERENCES \`summary_timesheet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`st_component\` ADD CONSTRAINT \`FK_5017ddb672ac0a9840caff2a2db\` FOREIGN KEY (\`contractServiceId\`) REFERENCES \`contract_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`st_component\` ADD CONSTRAINT \`FK_9f515d3e4cc18b5338fcf86cb8f\` FOREIGN KEY (\`shorebaseServiceId\`) REFERENCES \`shorebase_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`st_component\` ADD CONSTRAINT \`FK_404a2583f02381f074b3c03fc3b\` FOREIGN KEY (\`uomCode\`) REFERENCES \`uo_m\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`st_component\` ADD CONSTRAINT \`FK_37f92f309784509be70e3998f3b\` FOREIGN KEY (\`contractServicePriceId\`) REFERENCES \`contract_service_price\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`st_component\` ADD CONSTRAINT \`FK_ec5b6641a28e8cb33d113ec63f0\` FOREIGN KEY (\`shorebaseServicePriceId\`) REFERENCES \`shorebase_service_price\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shorebase_service_price\` ADD CONSTRAINT \`FK_16b2727adb783febb7ee7e9690a\` FOREIGN KEY (\`shorebaseServicesId\`) REFERENCES \`shorebase_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shorebase_service_price\` ADD CONSTRAINT \`FK_af159e3194846d93125b4c1b77a\` FOREIGN KEY (\`companiesId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shorebase_service\` ADD CONSTRAINT \`FK_a23933f30d8338cce10b6ef3e37\` FOREIGN KEY (\`uomCode\`) REFERENCES \`uo_m\`(\`code\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_service\` ADD CONSTRAINT \`FK_ab4908f934e19efecd3cc0ccff7\` FOREIGN KEY (\`contractId\`) REFERENCES \`contract\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`contract_service\` ADD CONSTRAINT \`FK_7dec02d521c575cf1f55df3b932\` FOREIGN KEY (\`serviceId\`) REFERENCES \`shorebase_service\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`contract_service\` ADD CONSTRAINT \`FK_78105770539c69cb46bdddfdd9b\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`contract_service\` ADD CONSTRAINT \`FK_f4005961d8229d33d53d7b559a2\` FOREIGN KEY (\`uomCode\`) REFERENCES \`uo_m\`(\`code\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`contract_service\` ADD CONSTRAINT \`FK_b82abe7c9b5dc54607f6060a057\` FOREIGN KEY (\`sumCalcCode\`) REFERENCES \`sum_calc\`(\`code\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`job_position\` ADD CONSTRAINT \`FK_a48be881b0d9f82bd365e78a7d1\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`job_position\` ADD CONSTRAINT \`FK_a0a0ead0674b0090e019719078c\` FOREIGN KEY (\`jobTitleId\`) REFERENCES \`job_title\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`job_position\` ADD CONSTRAINT \`FK_eca49de26436029306669ba2553\` FOREIGN KEY (\`parentId\`) REFERENCES \`job_position\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`job_position\` DROP FOREIGN KEY \`FK_eca49de26436029306669ba2553\``);
        await queryRunner.query(`ALTER TABLE \`job_position\` DROP FOREIGN KEY \`FK_a0a0ead0674b0090e019719078c\``);
        await queryRunner.query(`ALTER TABLE \`job_position\` DROP FOREIGN KEY \`FK_a48be881b0d9f82bd365e78a7d1\``);
        await queryRunner.query(`ALTER TABLE \`contract_service\` DROP FOREIGN KEY \`FK_b82abe7c9b5dc54607f6060a057\``);
        await queryRunner.query(`ALTER TABLE \`contract_service\` DROP FOREIGN KEY \`FK_f4005961d8229d33d53d7b559a2\``);
        await queryRunner.query(`ALTER TABLE \`contract_service\` DROP FOREIGN KEY \`FK_78105770539c69cb46bdddfdd9b\``);
        await queryRunner.query(`ALTER TABLE \`contract_service\` DROP FOREIGN KEY \`FK_7dec02d521c575cf1f55df3b932\``);
        await queryRunner.query(`ALTER TABLE \`contract_service\` DROP FOREIGN KEY \`FK_ab4908f934e19efecd3cc0ccff7\``);
        await queryRunner.query(`ALTER TABLE \`shorebase_service\` DROP FOREIGN KEY \`FK_a23933f30d8338cce10b6ef3e37\``);
        await queryRunner.query(`ALTER TABLE \`shorebase_service_price\` DROP FOREIGN KEY \`FK_af159e3194846d93125b4c1b77a\``);
        await queryRunner.query(`ALTER TABLE \`shorebase_service_price\` DROP FOREIGN KEY \`FK_16b2727adb783febb7ee7e9690a\``);
        await queryRunner.query(`ALTER TABLE \`st_component\` DROP FOREIGN KEY \`FK_ec5b6641a28e8cb33d113ec63f0\``);
        await queryRunner.query(`ALTER TABLE \`st_component\` DROP FOREIGN KEY \`FK_37f92f309784509be70e3998f3b\``);
        await queryRunner.query(`ALTER TABLE \`st_component\` DROP FOREIGN KEY \`FK_404a2583f02381f074b3c03fc3b\``);
        await queryRunner.query(`ALTER TABLE \`st_component\` DROP FOREIGN KEY \`FK_9f515d3e4cc18b5338fcf86cb8f\``);
        await queryRunner.query(`ALTER TABLE \`st_component\` DROP FOREIGN KEY \`FK_5017ddb672ac0a9840caff2a2db\``);
        await queryRunner.query(`ALTER TABLE \`st_component\` DROP FOREIGN KEY \`FK_c274a8a1ba06a6d7aee8b13ada3\``);
        await queryRunner.query(`ALTER TABLE \`contract_service_price\` DROP FOREIGN KEY \`FK_03d9f74aa59619046e86d08f7b8\``);
        await queryRunner.query(`ALTER TABLE \`st_timesheet\` DROP FOREIGN KEY \`FK_b8dc581b044bc5bede6e6dba8fc\``);
        await queryRunner.query(`ALTER TABLE \`timesheet\` DROP FOREIGN KEY \`FK_496744bcf637a12e544804e2d88\``);
        await queryRunner.query(`ALTER TABLE \`timesheet\` DROP FOREIGN KEY \`FK_727931c1dbed8548e8c3a21697c\``);
        await queryRunner.query(`ALTER TABLE \`timesheet\` DROP FOREIGN KEY \`FK_20fe7c662cd0dfc3a38979e4630\``);
        await queryRunner.query(`ALTER TABLE \`timesheet\` DROP FOREIGN KEY \`FK_37349385c493b325e4ef4671078\``);
        await queryRunner.query(`ALTER TABLE \`timesheet\` DROP FOREIGN KEY \`FK_34e68bf7bcf593c3b40436a13a3\``);
        await queryRunner.query(`ALTER TABLE \`timesheet\` DROP FOREIGN KEY \`FK_311d5e800cd6b644d427a2d34b9\``);
        await queryRunner.query(`ALTER TABLE \`timesheet_activity\` DROP FOREIGN KEY \`FK_9f1c03e7735a96b1e5497f553cb\``);
        await queryRunner.query(`ALTER TABLE \`timesheet_activity\` DROP FOREIGN KEY \`FK_97a61b2c03ed827486806ab451e\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_a3be35ce844d95f1a4ec75b3852\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_cd03d765b6008f724fccb3c1cd7\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_d6283f57727d60c94cc72a31916\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_097e3a0060d8378f8676f57f879\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_6f5deb55ae067e8a056322ece9a\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_878912d8dd0561d68f53c0f3a37\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_9e33c5fd2fb069d6ed3974496a7\``);
        await queryRunner.query(`ALTER TABLE \`sub_contractor\` DROP FOREIGN KEY \`FK_a02d4c72cafec665def1782a7e3\``);
        await queryRunner.query(`ALTER TABLE \`sub_contractor\` DROP FOREIGN KEY \`FK_90e28e0a19230b5d4a392f7a162\``);
        await queryRunner.query(`ALTER TABLE \`contract\` DROP FOREIGN KEY \`FK_ba4311c222bf9285d9d06f3b477\``);
        await queryRunner.query(`ALTER TABLE \`approval_workflow\` DROP FOREIGN KEY \`FK_b5c938c6c1e5d01e98609949909\``);
        await queryRunner.query(`ALTER TABLE \`approval_workflow\` DROP FOREIGN KEY \`FK_8cf501bac996196ccd9a946f1df\``);
        await queryRunner.query(`ALTER TABLE \`approval_workflow\` DROP FOREIGN KEY \`FK_1c216785ba911e94965fa534ca2\``);
        await queryRunner.query(`ALTER TABLE \`approval_workflow\` DROP FOREIGN KEY \`FK_bf9bab0e130a0679814fc01ab51\``);
        await queryRunner.query(`ALTER TABLE \`approval_workflow_stage\` DROP FOREIGN KEY \`FK_3885d1beda753ab0d593af75f0f\``);
        await queryRunner.query(`ALTER TABLE \`approval_workflow_stage\` DROP FOREIGN KEY \`FK_d2286d604120f793499ce8b419e\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_f51cce93e344f0ec434dfa2b49a\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_2c03b114e16befcc99d77a7bc2f\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_f72b9f75117746878f7b44012ee\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_48df81ae866b7affa930dff4b79\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_d4d9962befb2715a006e1b9a633\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_1cfbcd649d77e715d8595e2fbb3\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_d7fe65cdd32f9c504a9b4797278\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_f3b13e6a0dd01b4baa7674a47dc\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_289341bdda412b7fd1e1e49d35a\``);
        await queryRunner.query(`ALTER TABLE \`approval\` DROP FOREIGN KEY \`FK_6a05161b24197a85d8067fce714\``);
        await queryRunner.query(`ALTER TABLE \`summary_timesheet\` DROP FOREIGN KEY \`FK_7e039b0bf55489b9f9f6a21ffa9\``);
        await queryRunner.query(`ALTER TABLE \`summary_timesheet\` DROP FOREIGN KEY \`FK_addde76f5823a21d75d9b5535da\``);
        await queryRunner.query(`ALTER TABLE \`summary_timesheet\` DROP FOREIGN KEY \`FK_ca34cf0b0c7bf4dc9c01fa5f326\``);
        await queryRunner.query(`ALTER TABLE \`user_signature\` DROP FOREIGN KEY \`FK_9e0019f81ef0e22e0f7945240f5\``);
        await queryRunner.query(`ALTER TABLE \`user_position\` DROP FOREIGN KEY \`FK_a181d19410343624fa0d3b268fb\``);
        await queryRunner.query(`ALTER TABLE \`user_position\` DROP FOREIGN KEY \`FK_1b7679d1ea0ca6182710e888fcb\``);
        await queryRunner.query(`DROP TABLE \`job_position\``);
        await queryRunner.query(`DROP TABLE \`job_title\``);
        await queryRunner.query(`DROP TABLE \`company\``);
        await queryRunner.query(`DROP TABLE \`contract_service\``);
        await queryRunner.query(`DROP TABLE \`sum_calc\``);
        await queryRunner.query(`DROP TABLE \`uo_m\``);
        await queryRunner.query(`DROP INDEX \`IDX_1c806db645eb23c78d6a95294e\` ON \`shorebase_service\``);
        await queryRunner.query(`DROP TABLE \`shorebase_service\``);
        await queryRunner.query(`DROP TABLE \`shorebase_service_price\``);
        await queryRunner.query(`DROP TABLE \`st_component\``);
        await queryRunner.query(`DROP TABLE \`contract_service_price\``);
        await queryRunner.query(`DROP TABLE \`st_timesheet\``);
        await queryRunner.query(`DROP TABLE \`timesheet\``);
        await queryRunner.query(`DROP TABLE \`timesheet_activity\``);
        await queryRunner.query(`DROP TABLE \`activity\``);
        await queryRunner.query(`DROP TABLE \`sub_contractor\``);
        await queryRunner.query(`DROP TABLE \`contract\``);
        await queryRunner.query(`DROP TABLE \`approval_workflow\``);
        await queryRunner.query(`DROP TABLE \`approval_workflow_stage\``);
        await queryRunner.query(`DROP TABLE \`approval\``);
        await queryRunner.query(`DROP TABLE \`invoice\``);
        await queryRunner.query(`DROP TABLE \`performa_invoice\``);
        await queryRunner.query(`DROP TABLE \`summary_timesheet\``);
        await queryRunner.query(`DROP TABLE \`timesheet_type\``);
        await queryRunner.query(`DROP INDEX \`IDX_278dcdc8d755d484eb020fc3b0\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`user_signature\``);
        await queryRunner.query(`DROP TABLE \`user_position\``);
        await queryRunner.query(`DROP TABLE \`approval_status\``);
        await queryRunner.query(`DROP TABLE \`approval_type\``);
        await queryRunner.query(`DROP TABLE \`activity_status\``);
    }

}
